var f;f||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m,p=!1,na,la=a=>a.startsWith("file://");
function oa(){var a=pa.buffer;r=new Int8Array(a);qa=new Int16Array(a);u=new Uint8Array(a);ra=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function sa(a){f.onAbort?.(a);a=`Aborted(${a})`;k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var qa,v,r,x,y,ra,w,u,ya=a=>{for(;0<a.length;)a.shift()(f)},za=[],Aa=[],Ba=()=>{var a=f.preRun.shift();Aa.push(a)},z=0,A=null,Ca=!0,Da=0,C={},Ea=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Fa=a=>{na=a;Ca||0<Da||(f.onExit?.(a),p=!0);fa(a,new xa(a))},Ga=()=>{if(!(Ca||0<Da))try{var a=na;na=a;Fa(a)}catch(b){Ea(b)}},Ha=a=>{if(!p)try{a()}catch(b){Ea(b)}finally{Ga()}},Oa=(a,b)=>{Ia=a;Ja=b;if(E)if(Ka||=!0,0==a)F=function(){setTimeout(G,Math.max(0,La+b-performance.now())|0)};else if(1==a)F=function(){Ma(G)};
else{if(!Na)if(globalThis.setImmediate)Na=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Na=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}F=function(){Na(G)}}},Xa=(a,b,c,d,e)=>{function h(){return g<Pa?(Ga(),!1):!0}E=a;Qa=d;var g=Pa;Ka=!1;G=function(){if(!p)if(0<Ra.length){var l=
Ra.shift();l.od(l.ad);if(Sa){var n=Sa,q=0==n%1?n-1:Math.floor(n);Sa=l.dd?q:(8*n+(q+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",n=Sa??0,q=Ta.ld??0,n?n<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(G,0)}else if(h())if(Ua=Ua+1|0,1==Ia&&1<Ja&&0!=Ua%Ja)F();else{0==Ia&&(La=performance.now());a:if(!p){for(l of Va)if(!1===l())break a;Ha(a);for(n of Wa)n()}h()&&F()}};e||(0<b?Oa(0,1E3/b):Oa(1,1),F());if(c)throw"unwind";},Ka=!1,F=
null,Pa=0,E=null,Qa=0,Ia=0,Ja=0,Ua=0,Ra=[],Va=[],Wa=[];function Ya(){F=null;Pa++}var Za=0;function Ma(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Za)Za=b+1E3/60;else for(;b+2>=Za;)Za+=1E3/60;setTimeout(a,Math.max(Za-b,0))}}
var Ta={},La,G,Na,Sa,$a=new TextDecoder,ab=(a,b,c)=>{for(c=b+c;a[b]&&!(b>=c);)++b;return b},H=(a,b)=>a?$a.decode(u.subarray(a,ab(u,a,b))):"",bb=[0,globalThis.document??0,globalThis.window??0],I=a=>{a=2<a?H(a):a;return bb[a]||globalThis.document?.querySelector(a)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};function db(a){var b=J.bc[a];b.target.removeEventListener(b.ac,b.Ic,b.ec);J.bc.splice(a,1)}
function eb(){if(navigator.userActivation?navigator.userActivation.isActive:J.uc&&J.Vc.rc){var a=J.jc;J.jc=[];for(var b of a)b.xc(...b.Ec)}}function K(a){if(!a.target)return-4;if(a.cc)a.Ic=function(c){++J.uc;J.Vc=a;eb();a.hc(c);eb();--J.uc},a.target.addEventListener(a.ac,a.Ic,a.ec),J.bc.push(a);else for(var b=0;b<J.bc.length;++b)J.bc[b].target==a.target&&J.bc[b].ac==a.ac&&db(b--);return 0}function fb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var J={bd:0,pd:0,vc:0,pc:0,Bc:0,zc:0,sc:0,jd:0,td:0,hd:0,tc:0,wc:0,Dd:0,yc:0,vd(){for(;J.bc.length;)db(J.bc.length-1);J.jc=[]},uc:0,jc:[],gd(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var e of J.jc)if(e.xc==a&&d(e.Ec,c))return;J.jc.push({xc:a,Mc:b,Ec:c});J.jc.sort((h,g)=>h.Mc-g.Mc)},xd(a){J.jc=J.jc.filter(b=>b.xc!=a)},bc:[],wd:(a,b)=>{for(var c=0;c<J.bc.length;++c)J.bc[c].target!=a||b&&b!=J.bc[c].ac||db(c--)},yd(a){let b=!1;for(let c=0;c<
J.bc.length;++c){const d=J.bc[c];d.target===a.target&&d.dc===a.dc&&d.cc===a.cc&&d.fc===a.fc&&(db(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},L=(a,b,c)=>{var d=u;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&
63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;h++}}d[b]=0;return b-e},gb=(a,b,c,d,e,h)=>{J.sc||(J.sc=M(256));a={target:I(a),ac:h,dc:e,fc:b,cc:d,hc:g=>{var l=g.target.id?g.target.id:"",n=J.sc;L(fb(g.target),n+0,128);L(l,n+128,128);N.get(d)(e,n,b)&&g.preventDefault()},ec:c};return K(a)},hb=(a,b,c,d,e)=>{J.tc||(J.tc=M(276));return K({target:a,ac:e,dc:19,fc:b,cc:d,hc:h=>{var g=J.tc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;r[g]=n;r[g+1]=J.fullscreenEnabled();var q=n?l:J.Zc,t=q?.id||"";L(fb(q),g+2,128);L(t,g+130,128);v[g+260>>2]=q?q.clientWidth:0;v[g+264>>2]=q?q.clientHeight:0;v[g+268>>2]=screen.width;v[g+272>>2]=screen.height;n&&(J.Zc=l);N.get(d)(19,g,b)&&h.preventDefault()},ec:c})},ib=(a,b,c,d,e,h)=>{J.vc||(J.vc=M(160));a={target:I(a),ac:h,dc:e,fc:b,cc:d,hc:g=>{var l=J.vc;y[l>>3]=g.timeStamp;var n=l>>2;v[n+2]=g.location;r[l+12]=g.ctrlKey;r[l+
13]=g.shiftKey;r[l+14]=g.altKey;r[l+15]=g.metaKey;r[l+16]=g.repeat;v[n+5]=g.charCode;v[n+6]=g.keyCode;v[n+7]=g.which;L(g.key||"",l+32,32);L(g.code||"",l+64,32);L(g.char||"",l+96,32);L(g.locale||"",l+128,32);N.get(d)(e,l,b)&&g.preventDefault()},ec:c};return K(a)},jb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;qa[2*d+14]=b.button;qa[2*d+15]=b.buttons;v[d+8]=b.movementX;
v[d+9]=b.movementY;a=cb(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},kb=(a,b,c,d,e,h)=>{J.pc||(J.pc=M(64));a=I(a);return K({target:a,rc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ac:h,dc:e,fc:b,cc:d,hc:g=>{jb(J.pc,g,a);N.get(d)(e,J.pc,b)&&g.preventDefault()},ec:c})},lb=(a,b,c,d)=>{J.wc||(J.wc=M(257));return K({target:a,ac:"pointerlockchange",dc:20,fc:b,cc:d,hc:e=>{var h=J.wc,g=document.pointerLockElement;r[h]=!!g;var l=g?.id||"";L(fb(g),h+1,128);L(l,h+129,128);N.get(d)(20,h,
b)&&e.preventDefault()},ec:c})},mb=(a,b,c,d)=>K({target:a,ac:"pointerlockerror",dc:38,fc:b,cc:d,hc:e=>{N.get(d)(38,0,b)&&e.preventDefault()},ec:c}),nb=(a,b,c,d)=>{J.zc||(J.zc=M(36));a=I(a);return K({target:a,ac:"resize",dc:10,fc:b,cc:d,hc:e=>{if(e.target==a){var h=document.body;if(h){var g=J.zc;v[g>>2]=0;v[g+4>>2]=h.clientWidth;v[g+8>>2]=h.clientHeight;v[g+12>>2]=innerWidth;v[g+16>>2]=innerHeight;v[g+20>>2]=outerWidth;v[g+24>>2]=outerHeight;v[g+28>>2]=pageXOffset|0;v[g+32>>2]=pageYOffset|0;N.get(d)(10,
g,b)&&e.preventDefault()}}},ec:c})},ob=(a,b,c,d,e,h)=>{J.yc||(J.yc=M(1552));a=I(a);return K({target:a,rc:"touchstart"==h||"touchend"==h,ac:h,dc:e,fc:b,cc:d,hc:g=>{var l={},n=g.touches;for(var q of n)q.Jc=q.Lc=0,l[q.identifier]=q;for(var t of g.changedTouches)t.Jc=1,l[t.identifier]=t;for(var B of g.targetTouches)l[B.identifier].Lc=1;n=J.yc;y[n>>3]=g.timeStamp;r[n+12]=g.ctrlKey;r[n+13]=g.shiftKey;r[n+14]=g.altKey;r[n+15]=g.metaKey;q=n+16;t=cb(a);B=0;for(let D of Object.values(l))if(l=q>>2,v[l]=D.identifier,
v[l+1]=D.screenX,v[l+2]=D.screenY,v[l+3]=D.clientX,v[l+4]=D.clientY,v[l+5]=D.pageX,v[l+6]=D.pageY,r[q+28]=D.Jc,r[q+29]=D.Lc,v[l+8]=D.clientX-(t.left|0),v[l+9]=D.clientY-(t.top|0),q+=48,31<++B)break;v[n+8>>2]=B;N.get(d)(e,n,b)&&g.preventDefault()},ec:c})},O,pb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,
d,e,h,g))},qb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},rb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},sb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},tb=1,P=[],Q=[],ub=[],vb=[],R=[],S=[],wb=[],xb=[],T=[],yb={},zb=4,Ab=0,Bb=a=>{for(var b=tb++,c=a.length;c<b;c++)a[c]=null;return b},V=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=O[c](),g=h&&Bb(d);h?(h.name=g,d[g]=h):U||=1282;v[b+4*e>>2]=g}},Db=(a,b)=>{a.Dc||(a.Dc=a.getContext,a.getContext=function(d,e){e=a.Dc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Kc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Cb(c,b):0},Cb=(a,b)=>{var c=Bb(xb),d={handle:c,attributes:b,version:b.Kc,Cc:a};a.canvas&&(a.canvas.$c=d);xb[c]=d;if("undefined"==typeof b.Hc||b.Hc)if((a=d)||(a=W),!a.Yc){a.Yc=!0;b=a.Cc;b.sd=b.getExtension("WEBGL_multi_draw");b.nd=b.getExtension("EXT_polygon_offset_clamp");b.md=b.getExtension("EXT_clip_control");b.Ed=b.getExtension("WEBGL_polygon_mode");pb(b);qb(b);rb(b);b.kd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.qd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Gc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Gc)b.Gc=b.getExtension("EXT_disjoint_timer_query");for(var e of sb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},U,W,Eb=(a,b,c,d,e,h)=>{a={target:I(a),ac:h,dc:e,fc:b,cc:d,hc:g=>{N.get(d)(e,0,b)&&g.preventDefault()},ec:c};K(a)},Fb=(a,b,c,d)=>{J.Bc||(J.Bc=M(96));return K({target:a,rc:!0,ac:"wheel",dc:9,fc:b,cc:d,hc:e=>{var h=J.Bc;jb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;
y[h+80>>3]=e.deltaZ;v[h+88>>2]=e.deltaMode;N.get(d)(9,h,b)&&e.preventDefault()},ec:c})},Gb=["default","low-power","high-performance"],Hb=[null,[],[]],Ib=[],Jb=()=>{var a=sb(O);return a=a.concat(a.map(b=>"GL_"+b))},Kb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>W.version){U||=1282;return}c=Jb().length;break;case 33307:case 33308:if(2>W.version){U||=1280;return}c=
33307==a?3:0}if(void 0===c)switch(d=O.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||
d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else U||=1281},Lb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},
Mb=a=>{var b=Lb(a)+1,c=M(b);c&&L(a,c,b);return c},Nb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ob=a=>{a-=5120;return 0==a?r:1==a?u:2==a?qa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:ra},X=a=>{var b=O.Wc;if(b){var c=b.lc[a];"number"==typeof c&&(b.lc[a]=c=O.getUniformLocation(b,b.Tc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},Y=[],Pb=[],Rb=a=>{var b=Lb(a)+1,c=Qb(b);L(a,c,b);return c},Ub=a=>{var b=Sb();a();Tb(b)};f.requestAnimationFrame=Ma;f.pauseMainLoop=Ya;
f.resumeMainLoop=function(){Pa++;var a=Ia,b=Ja,c=E;E=null;Xa(c,0,!1,Qa,!0);Oa(a,b);F()};f.preMainLoop&&Va.push(f.preMainLoop);f.postMainLoop&&Wa.push(f.postMainLoop);for(let a=0;32>a;++a)Ib.push(Array(a));for(var Vb=new Float32Array(288),Z=0;288>=Z;++Z)Y[Z]=Vb.subarray(0,Z);var Wb=new Int32Array(288);for(Z=0;288>=Z;++Z)Pb[Z]=Wb.subarray(0,Z);f.noExitRuntime&&(Ca=f.noExitRuntime);f.print&&(ma=f.print);f.printErr&&(k=f.printErr);f.wasmBinary&&(m=f.wasmBinary);f.arguments&&(da=f.arguments);
f.thisProgram&&(ea=f.thisProgram);if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();
var Xb,Yb,Zb,$b,ac,bc,cc,M,Tb,Qb,Sb,pa,N,dc={La:()=>sa(""),Ia:()=>{Ca=!1;Da=0},cb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ha(()=>cc(a,performance.now()))},b);C[a]={id:c,Cd:b};return 0},Ta:()=>{Ya();E=null},O:()=>globalThis.devicePixelRatio??1,na:(a,b,c)=>{a=I(a);if(!a)return-4;a=cb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Ua:()=>performance.now(),Za:(a,b)=>{function c(d){N.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
Pa:a=>{var b=u.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);oa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},Q:(a,b,c,d)=>gb(a,b,c,d,12,"blur"),L:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},R:(a,b,c,d)=>gb(a,b,c,d,13,"focus"),P:(a,b,c,d)=>{if(!J.fullscreenEnabled())return-1;a=I(a);if(!a)return-4;
hb(a,b,c,d,"webkitfullscreenchange");return hb(a,b,c,d,"fullscreenchange")},$:(a,b,c,d)=>ib(a,b,c,d,2,"keydown"),Z:(a,b,c,d)=>ib(a,b,c,d,1,"keypress"),_:(a,b,c,d)=>ib(a,b,c,d,3,"keyup"),_a:(a,b,c)=>{a=N.get(a);Xa(a,b,c)},ia:(a,b,c,d)=>kb(a,b,c,d,5,"mousedown"),da:(a,b,c,d)=>kb(a,b,c,d,33,"mouseenter"),ba:(a,b,c,d)=>kb(a,b,c,d,34,"mouseleave"),ea:(a,b,c,d)=>kb(a,b,c,d,8,"mousemove"),ga:(a,b,c,d)=>kb(a,b,c,d,6,"mouseup"),T:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?lb(a,b,c,d):-4:-1,S:(a,
b,c,d)=>document.body?.requestPointerLock?(a=I(a))?mb(a,b,c,d):-4:-1,Y:(a,b,c,d)=>nb(a,b,c,d),U:(a,b,c,d)=>ob(a,b,c,d,25,"touchcancel"),V:(a,b,c,d)=>ob(a,b,c,d,23,"touchend"),W:(a,b,c,d)=>ob(a,b,c,d,24,"touchmove"),X:(a,b,c,d)=>ob(a,b,c,d,22,"touchstart"),N:(a,b,c,d)=>{Eb(a,b,c,d,31,"webglcontextlost");return 0},M:(a,b,c,d)=>{Eb(a,b,c,d,32,"webglcontextrestored");return 0},aa:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?Fb(a,b,c,d):-1:-4,ua:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],
stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Gb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Kc:v[c+4],rd:v[c+5],Hc:r[b+24],Xc:r[b+25],ud:v[c+7],zd:r[b+32]};a=I(a);return!a||b.Xc?0:Db(a,b)},sa:a=>{W=xb[a];f.ctx=O=W?.Cc;return!a||O?0:-5},Oa:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var g=w[b>>2],l=w[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=a,t=u[g+n],B=Hb[q];0===t||10===t?(q=1===q?ma:k,t=ab(B,0),t=$a.decode(B.buffer?B.subarray(0,t):new Uint8Array(B.slice(0,
t))),q(t),B.length=0):B.push(t)}e+=l}w[d>>2]=e;return 0},v:a=>O.activeTexture(a),r:(a,b)=>{O.attachShader(Q[a],S[b])},b:(a,b)=>{35051==a?O.Fc=b:35052==a&&(O.kc=b);O.bindBuffer(a,P[b])},fa:(a,b,c)=>{O.bindBufferBase(a,b,P[c])},Kb:(a,b,c,d,e)=>{O.bindBufferRange(a,b,P[c],d,e)},f:(a,b)=>{O.bindFramebuffer(a,ub[b])},va:(a,b)=>{O.bindRenderbuffer(a,vb[b])},u:(a,b)=>{O.bindSampler(a,T[b])},g:(a,b)=>{O.bindTexture(a,R[b])},K:a=>{O.bindVertexArray(wb[a])},la:(a,b,c,d)=>O.blendColor(a,b,c,d),ma:(a,b)=>O.blendEquationSeparate(a,
b),w:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),rb:(a,b,c,d,e,h,g,l,n,q)=>O.blitFramebuffer(a,b,c,d,e,h,g,l,n,q),Ga:(a,b,c,d)=>{2<=W.version?c&&b?O.bufferData(a,u,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?u.subarray(c,c+b):b,d)},G:(a,b,c,d)=>{2<=W.version?c&&O.bufferSubData(a,b,u,d,c):O.bufferSubData(a,b,u.subarray(d,d+c))},db:a=>O.checkFramebufferStatus(a),ra:(a,b,c,d)=>O.clearBufferfi(a,b,c,d),y:(a,b,c)=>{O.clearBufferfv(a,b,x,c>>2)},qa:(a,b,c)=>{O.clearBufferiv(a,b,v,c>>2)},n:(a,b,c,d)=>{O.colorMask(!!a,
!!b,!!c,!!d)},gb:a=>{O.compileShader(S[a])},mb:(a,b,c,d,e,h,g,l,n)=>{2<=W.version?O.kc||!l?O.compressedTexSubImage2D(a,b,c,d,e,h,g,l,n):O.compressedTexSubImage2D(a,b,c,d,e,h,g,u,n,l):O.compressedTexSubImage2D(a,b,c,d,e,h,g,u.subarray(n,n+l))},kb:(a,b,c,d,e,h,g,l,n,q,t)=>{O.kc?O.compressedTexSubImage3D(a,b,c,d,e,h,g,l,n,q,t):O.compressedTexSubImage3D(a,b,c,d,e,h,g,l,n,u,t,q)},Ba:()=>{var a=Bb(Q),b=O.createProgram();b.name=a;b.oc=b.mc=b.nc=0;b.Ac=1;Q[a]=b;return a},ib:a=>{var b=Bb(S);S[b]=O.createShader(a);
return b},ka:a=>O.cullFace(a),nb:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=P[d];e&&(O.deleteBuffer(e),e.name=0,P[d]=null,d==O.Fc&&(O.Fc=0),d==O.kc&&(O.kc=0))}},s:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=ub[d];e&&(O.deleteFramebuffer(e),e.name=0,ub[d]=null)}},k:a=>{if(a){var b=Q[a];b?(O.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},H:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=vb[d];e&&(O.deleteRenderbuffer(e),e.name=0,vb[d]=null)}},I:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*
c>>2],e=T[d];e&&(O.deleteSampler(e),e.name=0,T[d]=null)}},j:a=>{if(a){var b=S[a];b?(O.deleteShader(b),S[a]=null):U||=1281}},o:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=R[d];e&&(O.deleteTexture(e),e.name=0,R[d]=null)}},Ja:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];O.deleteVertexArray(wb[d]);wb[d]=null}},p:a=>O.depthFunc(a),q:a=>{O.depthMask(!!a)},c:a=>O.disable(a),ha:a=>{O.disableVertexAttribArray(a)},tb:(a,b,c)=>{O.drawArrays(a,b,c)},ub:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},B:(a,
b)=>{for(var c=Ib[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];O.drawBuffers(c)},vb:(a,b,c,d)=>{O.drawElements(a,b,c,d)},wb:(a,b,c,d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},e:a=>O.enable(a),Gb:a=>{O.enableVertexAttribArray(a)},i:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,vb[d])},h:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,R[d],e)},eb:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,b,R[c],d,e)},ja:a=>O.frontFace(a),Ha:(a,b)=>{V(a,b,"createBuffer",P)},J:(a,b)=>{V(a,b,"createFramebuffer",ub)},wa:(a,b)=>{V(a,b,"createRenderbuffer",
vb)},Ca:(a,b)=>{V(a,b,"createSampler",T)},Fa:(a,b)=>{V(a,b,"createTexture",R)},Ma:(a,b)=>{V(a,b,"createVertexArray",wb)},xa:(a,b)=>O.getAttribLocation(Q[a],H(b)),a:(a,b)=>Kb(a,b),za:(a,b,c,d)=>{a=O.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},D:(a,b,c)=>{if(c)if(a>=tb)U||=1281;else if(a=Q[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.oc){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.oc=
Math.max(a.oc,O.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.oc}else if(35722==b){if(!a.mc)for(d=O.getProgramParameter(a,35721),b=0;b<d;++b)a.mc=Math.max(a.mc,O.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.mc}else if(35381==b){if(!a.nc)for(d=O.getProgramParameter(a,35382),b=0;b<d;++b)a.nc=Math.max(a.nc,O.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.nc}else v[c>>2]=O.getProgramParameter(a,b);else U||=1281},fb:(a,b,c,d)=>{a=O.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?
L(a,d,b):0;c&&(v[c>>2]=b)},ca:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(S[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=O.getShaderParameter(S[a],b):U||=1281},Na:(a,b)=>{if(2>W.version)return U||=1282,0;var c=yb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Jb().map(Mb),c=yb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},C:(a,b)=>{b=H(b);if(a=Q[a]){var c=a,d=c.lc,
e=c.Uc,h;if(!d){c.lc=d={};c.Tc={};var g=O.getProgramParameter(c,35718);for(h=0;h<g;++h){var l=O.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Nb(n);q=0<q?n.slice(0,q):n;var t=c.Ac;c.Ac+=l;e[q]=[l,t];for(n=0;n<l;++n)d[t]=n,c.Tc[t++]=q}}c=a.lc;d=0;e=b;h=Nb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Uc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else U||=1281;return-1},qb:(a,b,c)=>{for(var d=Ib[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];O.invalidateFramebuffer(a,
d)},E:a=>{a=Q[a];O.linkProgram(a);a.lc=0;a.Uc={}},Ka:(a,b)=>{3317==a?zb=b:3314==a&&(Ab=b);O.pixelStorei(a,b)},x:(a,b)=>O.polygonOffset(a,b),sb:a=>O.readBuffer(a),ta:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),F:(a,b,c)=>{O.samplerParameterf(T[a],b,c)},d:(a,b,c)=>{O.samplerParameteri(T[a],b,c)},z:(a,b,c,d)=>O.scissor(a,b,c,d),hb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h)e+=H(w[c+4*h>>2],d?w[d+4*h>>2]:void 0);O.shaderSource(S[a],e)},pb:(a,b,c)=>O.stencilFunc(a,b,c),pa:(a,b,c,d)=>O.stencilFuncSeparate(a,
b,c,d),m:a=>O.stencilMask(a),ob:(a,b,c)=>O.stencilOp(a,b,c),oa:(a,b,c,d)=>O.stencilOpSeparate(a,b,c,d),Ea:(a,b,c,d,e)=>O.texStorage2D(a,b,c,d,e),Da:(a,b,c,d,e,h)=>O.texStorage3D(a,b,c,d,e,h),lb:(a,b,c,d,e,h,g,l,n)=>{if(2<=W.version){if(O.kc){O.texSubImage2D(a,b,c,d,e,h,g,l,n);return}if(n){var q=Ob(l);O.texSubImage2D(a,b,c,d,e,h,g,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Ob(l);var t=h*((Ab||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT+
zb-1&-zb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+t>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;O.texSubImage2D(a,b,c,d,e,h,g,l,n)},jb:(a,b,c,d,e,h,g,l,n,q,t)=>{if(O.kc)O.texSubImage3D(a,b,c,d,e,h,g,l,n,q,t);else if(t){var B=Ob(q);O.texSubImage3D(a,b,c,d,e,h,g,l,n,q,B,t>>>31-Math.clz32(B.BYTES_PER_ELEMENT))}else O.texSubImage3D(a,b,c,d,e,h,g,l,n,q,null)},Fb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1fv(X(a),x,c>>2,b);else{if(288>=b)for(var d=Y[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=
x.subarray(c>>2,c+4*b>>2);O.uniform1fv(X(a),d)}},ya:(a,b)=>{O.uniform1i(X(a),b)},Bb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1iv(X(a),v,c>>2,b);else{if(288>=b)for(var d=Pb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);O.uniform1iv(X(a),d)}},Eb:(a,b,c)=>{if(2<=W.version)b&&O.uniform2fv(X(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Y[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);O.uniform2fv(X(a),d)}},Ab:(a,b,c)=>{if(2<=W.version)b&&O.uniform2iv(X(a),
v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Pb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);O.uniform2iv(X(a),d)}},Db:(a,b,c)=>{if(2<=W.version)b&&O.uniform3fv(X(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Y[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);O.uniform3fv(X(a),d)}},zb:(a,b,c)=>{if(2<=W.version)b&&O.uniform3iv(X(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Pb[b],e=0;e<b;e+=3)d[e]=
v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);O.uniform3iv(X(a),d)}},Cb:(a,b,c)=>{if(2<=W.version)b&&O.uniform4fv(X(a),x,c>>2,4*b);else{if(72>=b){var d=Y[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);O.uniform4fv(X(a),d)}},yb:(a,b,c)=>{if(2<=W.version)b&&O.uniform4iv(X(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Pb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+
(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);O.uniform4iv(X(a),d)}},xb:(a,b,c,d)=>{if(2<=W.version)b&&O.uniformMatrix4fv(X(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=Y[16*b],h=x;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=
x.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(X(a),!!c,e)}},l:a=>{a=Q[a];O.useProgram(a);O.Wc=a},Hb:(a,b)=>{O.vertexAttribDivisor(a,b)},Ib:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},Jb:(a,b,c,d,e,h)=>{O.vertexAttribPointer(a,b,c,!!d,e,h)},A:(a,b,c,d)=>O.viewport(a,b,c,d),Aa:Fa,bb:function(){f.Nc=a=>{0!=Zb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Nc)},ab:function(){f.Sc=a=>{const b=a.clipboardData.getData("text");Ub(()=>{const c=Rb(b);Yb(c)})};window.addEventListener("paste",
f.Sc)},$a:function(){f.Ad=[];f.Oc=b=>{b.stopPropagation();b.preventDefault()};f.Pc=b=>{b.stopPropagation();b.preventDefault()};f.Qc=b=>{b.stopPropagation();b.preventDefault()};f.Rc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Bd=c;$b(c.length);for(let e=0;e<c.length;e++)Ub(()=>{const h=Rb(c[e].name);ac(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);bc(b.clientX,b.clientY,d)};const a=f.ic;a.addEventListener("dragenter",f.Oc,!1);a.addEventListener("dragleave",
f.Pc,!1);a.addEventListener("dragover",f.Qc,!1);a.addEventListener("drop",f.Rc,!1)},Wa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Xa:function(a){f.qc&&(URL.revokeObjectURL(f.qc[a].cd),f.qc[a]=null)},Lb:function(a,b){0!==b&&(document.title=H(b));a=H(a);void 0!==f.canvas&&("object"===typeof f.canvas?bb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.ic=I(a);f.ic||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);f.ic.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Sa:function(){window.removeEventListener("beforeunload",f.Nc)},Ra:function(){window.removeEventListener("paste",f.Sc)},Qa:function(){const a=f.ic;a.removeEventListener("dragenter",f.Oc);a.removeEventListener("dragleave",f.Pc);a.removeEventListener("dragover",f.Qc);a.removeEventListener("drop",f.Rc)},t:function(){f.ic&&f.ic.requestPointerLock&&f.ic.requestPointerLock()},Ya:function(a,b,c){if(f.ic){if(0===
b)a="none";else if(0!=c)a=f.qc[a].ed;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.ic.style.cursor=a}},Va:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,
b);h.data.set(u.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)}};function ec(a=[]){var b=Xb;a.unshift(ea);var c=a.length,d=Qb(4*(c+1)),e=d,h;for(h of a)w[e>>2]=Rb(h),e+=4;w[e>>2]=0;try{var g=b(c,d);na=g;Fa(g)}catch(l){Ea(l)}}
function fc(a=da){function b(){f.calledRun=!0;if(!p){gc.Nb();f.onRuntimeInitialized?.();f.noInitialRun||ec(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();za.push(c)}ya(za)}}if(0<z)A=fc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ba();ya(Aa);0<z?A=fc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}var gc;
(async function(){function a(c){c=gc=c.exports;Xb=f._main=c.Ob;Yb=f.__sapp_emsc_onpaste=c.Pb;Zb=f.__sapp_html5_get_ask_leave_site=c.Qb;$b=f.__sapp_emsc_begin_drop=c.Rb;ac=f.__sapp_emsc_drop=c.Sb;bc=f.__sapp_emsc_end_drop=c.Tb;f.__sapp_emsc_invoke_fetch_cb=c.Ub;f.__sapp_emsc_set_fullscreen_flag=c.Vb;cc=c.Wb;M=c.Xb;Tb=c.Yb;Qb=c.Zb;Sb=c._b;pa=c.Mb;N=c.$b;oa();z--;f.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return gc}z++;f.monitorRunDependencies?.(z);var b={a:dc};if(f.instantiateWasm)return new Promise(c=>
{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ta??=f.locateFile?f.locateFile("sulkyos.wasm",ia):ia+"sulkyos.wasm";return a((await wa(b)).instance)})();fc();
