var f;f||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var k=console.error.bind(console),m,p=!1,ma,la=a=>a.startsWith("file://");
function na(a){f.onAbort?.(a);a=`Aborted(${a})`;k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var oa;async function pa(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==oa&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function qa(a,b){try{var c=await pa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),na(d)}}
async function ra(a){var b=oa;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return qa(b,a)}class sa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ta,r,t,v,w,ua,x,y,va=a=>{for(;0<a.length;)a.shift()(f)},wa=[],xa=[],ya=()=>{var a=f.preRun.shift();xa.push(a)},z=0,A=null,za=!0,Aa=0,B={},Ba=a=>{a instanceof sa||"unwind"==a||fa(1,a)},Ca=a=>{ma=a;za||0<Aa||(f.onExit?.(a),p=!0);fa(a,new sa(a))},Da=()=>{if(!(za||0<Aa))try{var a=ma;ma=a;Ca(a)}catch(b){Ba(b)}},Ea=a=>{if(!p)try{a()}catch(b){Ba(b)}finally{Da()}},La=(a,b)=>{Fa=a;Ga=b;if(D)if(Ha||=!0,0==a)E=function(){setTimeout(F,Math.max(0,Ia+b-performance.now())|0)};else if(1==a)E=function(){Ja(F)};
else{if(!Ka)if(globalThis.setImmediate)Ka=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ka=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}E=function(){Ka(F)}}},Ua=(a,b,c,d,e)=>{function h(){return g<Ma?(Da(),!1):!0}D=a;Na=d;var g=Ma;Ha=!1;F=function(){if(!p)if(0<Oa.length){var l=
Oa.shift();l.od(l.ad);if(Pa){var n=Pa,q=0==n%1?n-1:Math.floor(n);Pa=l.dd?q:(8*n+(q+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",n=Pa??0,q=Qa.ld??0,n?n<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(F,0)}else if(h())if(Ra=Ra+1|0,1==Fa&&1<Ga&&0!=Ra%Ga)E();else{0==Fa&&(Ia=performance.now());a:if(!p){for(l of Sa)if(!1===l())break a;Ea(a);for(n of Ta)n()}h()&&E()}};e||(0<b?La(0,1E3/b):La(1,1),E());if(c)throw"unwind";},Ha=!1,E=
null,Ma=0,D=null,Na=0,Fa=0,Ga=0,Ra=0,Oa=[],Sa=[],Ta=[];function Va(){E=null;Ma++}var Wa=0;function Ja(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Wa)Wa=b+1E3/60;else for(;b+2>=Wa;)Wa+=1E3/60;setTimeout(a,Math.max(Wa-b,0))}}
var Qa={},Ia,F,Ka,Pa,Xa=new TextDecoder,G=(a,b)=>{if(a){var c=a,d=y;for(b=c+b;d[c]&&!(c>=b);)++c;a=Xa.decode(y.subarray(a,c))}else a="";return a},Ya=[0,globalThis.document??0,globalThis.window??0],H=a=>{a=2<a?G(a):a;return Ya[a]||globalThis.document?.querySelector(a)},Za=a=>0>Ya.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};function $a(a){var b=I.bc[a];b.target.removeEventListener(b.ac,b.Ic,b.ec);I.bc.splice(a,1)}
function ab(){if(navigator.userActivation?navigator.userActivation.isActive:I.uc&&I.Vc.rc){var a=I.jc;I.jc=[];for(var b of a)b.xc(...b.Ec)}}function J(a){if(!a.target)return-4;if(a.cc)a.Ic=function(c){++I.uc;I.Vc=a;ab();a.hc(c);ab();--I.uc},a.target.addEventListener(a.ac,a.Ic,a.ec),I.bc.push(a);else for(var b=0;b<I.bc.length;++b)I.bc[b].target==a.target&&I.bc[b].ac==a.ac&&$a(b--);return 0}function bb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var I={bd:0,pd:0,vc:0,pc:0,Bc:0,zc:0,sc:0,jd:0,td:0,hd:0,tc:0,wc:0,Dd:0,yc:0,vd(){for(;I.bc.length;)$a(I.bc.length-1);I.jc=[]},uc:0,jc:[],gd(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var e of I.jc)if(e.xc==a&&d(e.Ec,c))return;I.jc.push({xc:a,Mc:b,Ec:c});I.jc.sort((h,g)=>h.Mc-g.Mc)},xd(a){I.jc=I.jc.filter(b=>b.xc!=a)},bc:[],wd:(a,b)=>{for(var c=0;c<I.bc.length;++c)I.bc[c].target!=a||b&&b!=I.bc[c].ac||$a(c--)},yd(a){let b=!1;for(let c=0;c<
I.bc.length;++c){const d=I.bc[c];d.target===a.target&&d.dc===a.dc&&d.cc===a.cc&&d.fc===a.fc&&($a(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},K=(a,b,c)=>{var d=y;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&
63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;h++}}d[b]=0;return b-e},cb=(a,b,c,d,e,h)=>{I.sc||(I.sc=L(256));a={target:H(a),ac:h,dc:e,fc:b,cc:d,hc:g=>{var l=g.target.id?g.target.id:"",n=I.sc;K(bb(g.target),n+0,128);K(l,n+128,128);M.get(d)(e,n,b)&&g.preventDefault()},ec:c};return J(a)},db=(a,b,c,d,e)=>{I.tc||(I.tc=L(276));return J({target:a,ac:e,dc:19,fc:b,cc:d,hc:h=>{var g=I.tc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;t[g]=n;t[g+1]=I.fullscreenEnabled();var q=n?l:I.Zc,u=q?.id||"";K(bb(q),g+2,128);K(u,g+130,128);r[g+260>>2]=q?q.clientWidth:0;r[g+264>>2]=q?q.clientHeight:0;r[g+268>>2]=screen.width;r[g+272>>2]=screen.height;n&&(I.Zc=l);M.get(d)(19,g,b)&&h.preventDefault()},ec:c})},eb=(a,b,c,d,e,h)=>{I.vc||(I.vc=L(160));a={target:H(a),ac:h,dc:e,fc:b,cc:d,hc:g=>{var l=I.vc;w[l>>3]=g.timeStamp;var n=l>>2;r[n+2]=g.location;t[l+12]=g.ctrlKey;t[l+
13]=g.shiftKey;t[l+14]=g.altKey;t[l+15]=g.metaKey;t[l+16]=g.repeat;r[n+5]=g.charCode;r[n+6]=g.keyCode;r[n+7]=g.which;K(g.key||"",l+32,32);K(g.code||"",l+64,32);K(g.char||"",l+96,32);K(g.locale||"",l+128,32);M.get(d)(e,l,b)&&g.preventDefault()},ec:c};return J(a)},fb=(a,b,c)=>{w[a>>3]=b.timeStamp;var d=a>>2;r[d+2]=b.screenX;r[d+3]=b.screenY;r[d+4]=b.clientX;r[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;ta[2*d+14]=b.button;ta[2*d+15]=b.buttons;r[d+8]=b.movementX;
r[d+9]=b.movementY;a=Za(c);r[d+10]=b.clientX-(a.left|0);r[d+11]=b.clientY-(a.top|0)},gb=(a,b,c,d,e,h)=>{I.pc||(I.pc=L(64));a=H(a);return J({target:a,rc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ac:h,dc:e,fc:b,cc:d,hc:g=>{fb(I.pc,g,a);M.get(d)(e,I.pc,b)&&g.preventDefault()},ec:c})},hb=(a,b,c,d)=>{I.wc||(I.wc=L(257));return J({target:a,ac:"pointerlockchange",dc:20,fc:b,cc:d,hc:e=>{var h=I.wc,g=document.pointerLockElement;t[h]=!!g;var l=g?.id||"";K(bb(g),h+1,128);K(l,h+129,128);M.get(d)(20,h,
b)&&e.preventDefault()},ec:c})},ib=(a,b,c,d)=>J({target:a,ac:"pointerlockerror",dc:38,fc:b,cc:d,hc:e=>{M.get(d)(38,0,b)&&e.preventDefault()},ec:c}),jb=(a,b,c,d)=>{I.zc||(I.zc=L(36));a=H(a);return J({target:a,ac:"resize",dc:10,fc:b,cc:d,hc:e=>{if(e.target==a){var h=document.body;if(h){var g=I.zc;r[g>>2]=0;r[g+4>>2]=h.clientWidth;r[g+8>>2]=h.clientHeight;r[g+12>>2]=innerWidth;r[g+16>>2]=innerHeight;r[g+20>>2]=outerWidth;r[g+24>>2]=outerHeight;r[g+28>>2]=pageXOffset|0;r[g+32>>2]=pageYOffset|0;M.get(d)(10,
g,b)&&e.preventDefault()}}},ec:c})},kb=(a,b,c,d,e,h)=>{I.yc||(I.yc=L(1552));a=H(a);return J({target:a,rc:"touchstart"==h||"touchend"==h,ac:h,dc:e,fc:b,cc:d,hc:g=>{var l={},n=g.touches;for(var q of n)q.Jc=q.Lc=0,l[q.identifier]=q;for(var u of g.changedTouches)u.Jc=1,l[u.identifier]=u;for(var N of g.targetTouches)l[N.identifier].Lc=1;n=I.yc;w[n>>3]=g.timeStamp;t[n+12]=g.ctrlKey;t[n+13]=g.shiftKey;t[n+14]=g.altKey;t[n+15]=g.metaKey;q=n+16;u=Za(a);N=0;for(let C of Object.values(l))if(l=q>>2,r[l]=C.identifier,
r[l+1]=C.screenX,r[l+2]=C.screenY,r[l+3]=C.clientX,r[l+4]=C.clientY,r[l+5]=C.pageX,r[l+6]=C.pageY,t[q+28]=C.Jc,t[q+29]=C.Lc,r[l+8]=C.clientX-(u.left|0),r[l+9]=C.clientY-(u.top|0),q+=48,31<++N)break;r[n+8>>2]=N;M.get(d)(e,n,b)&&g.preventDefault()},ec:c})},O,lb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,
d,e,h,g))},mb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},nb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},ob=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},pb=1,P=[],Q=[],qb=[],rb=[],R=[],S=[],sb=[],tb=[],T=[],ub={},vb=4,wb=0,xb=a=>{for(var b=pb++,c=a.length;c<b;c++)a[c]=null;return b},V=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=O[c](),g=h&&xb(d);h?(h.name=g,d[g]=h):U||=1282;r[b+4*e>>2]=g}},zb=(a,b)=>{a.Dc||(a.Dc=a.getContext,a.getContext=function(d,e){e=a.Dc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Kc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
yb(c,b):0},yb=(a,b)=>{var c=xb(tb),d={handle:c,attributes:b,version:b.Kc,Cc:a};a.canvas&&(a.canvas.$c=d);tb[c]=d;if("undefined"==typeof b.Hc||b.Hc)if((a=d)||(a=W),!a.Yc){a.Yc=!0;b=a.Cc;b.sd=b.getExtension("WEBGL_multi_draw");b.nd=b.getExtension("EXT_polygon_offset_clamp");b.md=b.getExtension("EXT_clip_control");b.Ed=b.getExtension("WEBGL_polygon_mode");lb(b);mb(b);nb(b);b.kd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.qd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Gc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Gc)b.Gc=b.getExtension("EXT_disjoint_timer_query");for(var e of ob(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},U,W,Ab=(a,b,c,d,e,h)=>{a={target:H(a),ac:h,dc:e,fc:b,cc:d,hc:g=>{M.get(d)(e,0,b)&&g.preventDefault()},ec:c};J(a)},Bb=(a,b,c,d)=>{I.Bc||(I.Bc=L(96));return J({target:a,rc:!0,ac:"wheel",dc:9,fc:b,cc:d,hc:e=>{var h=I.Bc;fb(h,e,a);w[h+64>>3]=e.deltaX;w[h+72>>3]=e.deltaY;
w[h+80>>3]=e.deltaZ;r[h+88>>2]=e.deltaMode;M.get(d)(9,h,b)&&e.preventDefault()},ec:c})},Cb=["default","low-power","high-performance"],Db=[],Eb=()=>{var a=ob(O);return a=a.concat(a.map(b=>"GL_"+b))},Fb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>W.version){U||=1282;return}c=Eb().length;break;case 33307:case 33308:if(2>W.version){U||=1280;return}c=33307==a?3:0}if(void 0===
c)switch(d=O.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=
0;a<d.length;++a)r[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}r[b>>2]=c}else U||=1281},Gb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Hb=a=>{var b=Gb(a)+
1,c=L(b);c&&K(a,c,b);return c},Ib=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Jb=a=>{a-=5120;return 0==a?t:1==a?y:2==a?ta:4==a?r:6==a?v:5==a||28922==a||28520==a||30779==a||30782==a?x:ua},X=a=>{var b=O.Wc;if(b){var c=b.lc[a];"number"==typeof c&&(b.lc[a]=c=O.getUniformLocation(b,b.Tc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},Y=[],Kb=[],Mb=a=>{var b=Gb(a)+1,c=Lb(b);K(a,c,b);return c},Pb=a=>{var b=Nb();a();Ob(b)};f.requestAnimationFrame=Ja;f.pauseMainLoop=Va;
f.resumeMainLoop=function(){Ma++;var a=Fa,b=Ga,c=D;D=null;Ua(c,0,!1,Na,!0);La(a,b);E()};f.preMainLoop&&Sa.push(f.preMainLoop);f.postMainLoop&&Ta.push(f.postMainLoop);for(let a=0;32>a;++a)Db.push(Array(a));for(var Qb=new Float32Array(288),Z=0;288>=Z;++Z)Y[Z]=Qb.subarray(0,Z);var Rb=new Int32Array(288);for(Z=0;288>=Z;++Z)Kb[Z]=Rb.subarray(0,Z);f.noExitRuntime&&(za=f.noExitRuntime);f.printErr&&(k=f.printErr);f.wasmBinary&&(m=f.wasmBinary);f.arguments&&(da=f.arguments);f.thisProgram&&(ea=f.thisProgram);
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();
var Sb,Tb,Ub,Vb,Wb,Xb,Yb,L,Ob,Lb,Nb,Zb,M,$b={Ma:()=>na(""),Ia:()=>{za=!1;Aa=0},cb:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Ea(()=>Yb(a,performance.now()))},b);B[a]={id:c,Cd:b};return 0},Ta:()=>{Va();D=null},P:()=>globalThis.devicePixelRatio??1,oa:(a,b,c)=>{a=H(a);if(!a)return-4;a=Za(a);w[b>>3]=a.width;w[c>>3]=a.height;return 0},Ua:()=>performance.now(),Za:(a,b)=>{function c(d){M.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
Pa:()=>{na("OOM")},R:(a,b,c,d)=>cb(a,b,c,d,12,"blur"),M:(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},S:(a,b,c,d)=>cb(a,b,c,d,13,"focus"),Q:(a,b,c,d)=>{if(!I.fullscreenEnabled())return-1;a=H(a);if(!a)return-4;db(a,b,c,d,"webkitfullscreenchange");return db(a,b,c,d,"fullscreenchange")},aa:(a,b,c,d)=>eb(a,b,c,d,2,"keydown"),_:(a,b,c,d)=>eb(a,b,c,d,1,"keypress"),$:(a,b,c,d)=>eb(a,b,c,d,3,"keyup"),_a:(a,b,c)=>{a=M.get(a);Ua(a,b,c)},ja:(a,b,c,d)=>gb(a,b,c,d,5,"mousedown"),fa:(a,b,c,d)=>
gb(a,b,c,d,33,"mouseenter"),ca:(a,b,c,d)=>gb(a,b,c,d,34,"mouseleave"),ga:(a,b,c,d)=>gb(a,b,c,d,8,"mousemove"),ia:(a,b,c,d)=>gb(a,b,c,d,6,"mouseup"),U:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?hb(a,b,c,d):-4:-1,T:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?ib(a,b,c,d):-4:-1,Z:(a,b,c,d)=>jb(a,b,c,d),V:(a,b,c,d)=>kb(a,b,c,d,25,"touchcancel"),W:(a,b,c,d)=>kb(a,b,c,d,23,"touchend"),X:(a,b,c,d)=>kb(a,b,c,d,24,"touchmove"),Y:(a,b,c,d)=>kb(a,b,c,d,22,"touchstart"),O:(a,b,c,d)=>{Ab(a,
b,c,d,31,"webglcontextlost");return 0},N:(a,b,c,d)=>{Ab(a,b,c,d,32,"webglcontextrestored");return 0},ba:(a,b,c,d)=>(a=H(a))?"undefined"!=typeof a.onwheel?Bb(a,b,c,d):-1:-4,ua:(a,b)=>{var c=b>>2;b={alpha:!!t[b+0],depth:!!t[b+1],stencil:!!t[b+2],antialias:!!t[b+3],premultipliedAlpha:!!t[b+4],preserveDrawingBuffer:!!t[b+5],powerPreference:Cb[r[c+2]],failIfMajorPerformanceCaveat:!!t[b+12],Kc:r[c+4],rd:r[c+5],Hc:t[b+24],Xc:t[b+25],ud:r[c+7],zd:t[b+32]};a=H(a);return!a||b.Xc?0:zb(a,b)},ta:a=>{W=tb[a];f.ctx=
O=W?.Cc;return!a||O?0:-5},v:a=>O.activeTexture(a),r:(a,b)=>{O.attachShader(Q[a],S[b])},b:(a,b)=>{35051==a?O.Fc=b:35052==a&&(O.kc=b);O.bindBuffer(a,P[b])},ha:(a,b,c)=>{O.bindBufferBase(a,b,P[c])},Kb:(a,b,c,d,e)=>{O.bindBufferRange(a,b,P[c],d,e)},f:(a,b)=>{O.bindFramebuffer(a,qb[b])},wa:(a,b)=>{O.bindRenderbuffer(a,rb[b])},u:(a,b)=>{O.bindSampler(a,T[b])},g:(a,b)=>{O.bindTexture(a,R[b])},L:a=>{O.bindVertexArray(sb[a])},na:(a,b,c,d)=>O.blendColor(a,b,c,d),w:(a,b)=>O.blendEquationSeparate(a,b),x:(a,b,
c,d)=>O.blendFuncSeparate(a,b,c,d),rb:(a,b,c,d,e,h,g,l,n,q)=>O.blitFramebuffer(a,b,c,d,e,h,g,l,n,q),Ha:(a,b,c,d)=>{2<=W.version?c&&b?O.bufferData(a,y,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?y.subarray(c,c+b):b,d)},H:(a,b,c,d)=>{2<=W.version?c&&O.bufferSubData(a,b,y,d,c):O.bufferSubData(a,b,y.subarray(d,d+c))},db:a=>O.checkFramebufferStatus(a),sa:(a,b,c,d)=>O.clearBufferfi(a,b,c,d),z:(a,b,c)=>{O.clearBufferfv(a,b,v,c>>2)},ra:(a,b,c)=>{O.clearBufferiv(a,b,r,c>>2)},n:(a,b,c,d)=>{O.colorMask(!!a,
!!b,!!c,!!d)},gb:a=>{O.compileShader(S[a])},mb:(a,b,c,d,e,h,g,l,n)=>{2<=W.version?O.kc||!l?O.compressedTexSubImage2D(a,b,c,d,e,h,g,l,n):O.compressedTexSubImage2D(a,b,c,d,e,h,g,y,n,l):O.compressedTexSubImage2D(a,b,c,d,e,h,g,y.subarray(n,n+l))},kb:(a,b,c,d,e,h,g,l,n,q,u)=>{O.kc?O.compressedTexSubImage3D(a,b,c,d,e,h,g,l,n,q,u):O.compressedTexSubImage3D(a,b,c,d,e,h,g,l,n,y,u,q)},Ca:()=>{var a=xb(Q),b=O.createProgram();b.name=a;b.oc=b.mc=b.nc=0;b.Ac=1;Q[a]=b;return a},ib:a=>{var b=xb(S);S[b]=O.createShader(a);
return b},ma:a=>O.cullFace(a),nb:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=P[d];e&&(O.deleteBuffer(e),e.name=0,P[d]=null,d==O.Fc&&(O.Fc=0),d==O.kc&&(O.kc=0))}},s:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+4*c>>2],e=qb[d];e&&(O.deleteFramebuffer(e),e.name=0,qb[d]=null)}},k:a=>{if(a){var b=Q[a];b?(O.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},I:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=rb[d];e&&(O.deleteRenderbuffer(e),e.name=0,rb[d]=null)}},J:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*
c>>2],e=T[d];e&&(O.deleteSampler(e),e.name=0,T[d]=null)}},j:a=>{if(a){var b=S[a];b?(O.deleteShader(b),S[a]=null):U||=1281}},o:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=R[d];e&&(O.deleteTexture(e),e.name=0,R[d]=null)}},Ka:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2];O.deleteVertexArray(sb[d]);sb[d]=null}},p:a=>O.depthFunc(a),q:a=>{O.depthMask(!!a)},c:a=>O.disable(a),ka:a=>{O.disableVertexAttribArray(a)},tb:(a,b,c)=>{O.drawArrays(a,b,c)},ub:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},C:(a,
b)=>{for(var c=Db[a],d=0;d<a;d++)c[d]=r[b+4*d>>2];O.drawBuffers(c)},vb:(a,b,c,d)=>{O.drawElements(a,b,c,d)},wb:(a,b,c,d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},e:a=>O.enable(a),Gb:a=>{O.enableVertexAttribArray(a)},i:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,rb[d])},h:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,R[d],e)},eb:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,b,R[c],d,e)},la:a=>O.frontFace(a),Ja:(a,b)=>{V(a,b,"createBuffer",P)},K:(a,b)=>{V(a,b,"createFramebuffer",qb)},xa:(a,b)=>{V(a,b,"createRenderbuffer",
rb)},Da:(a,b)=>{V(a,b,"createSampler",T)},Ga:(a,b)=>{V(a,b,"createTexture",R)},Na:(a,b)=>{V(a,b,"createVertexArray",sb)},ya:(a,b)=>O.getAttribLocation(Q[a],G(b)),a:(a,b)=>Fb(a,b),Aa:(a,b,c,d)=>{a=O.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(r[c>>2]=b)},E:(a,b,c)=>{if(c)if(a>=pb)U||=1281;else if(a=Q[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(35719==b){if(!a.oc){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.oc=
Math.max(a.oc,O.getActiveUniform(a,b).name.length+1)}r[c>>2]=a.oc}else if(35722==b){if(!a.mc)for(d=O.getProgramParameter(a,35721),b=0;b<d;++b)a.mc=Math.max(a.mc,O.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.mc}else if(35381==b){if(!a.nc)for(d=O.getProgramParameter(a,35382),b=0;b<d;++b)a.nc=Math.max(a.nc,O.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.nc}else r[c>>2]=O.getProgramParameter(a,b);else U||=1281},fb:(a,b,c,d)=>{a=O.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?
K(a,d,b):0;c&&(r[c>>2]=b)},ea:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(S[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=O.getShaderParameter(S[a],b):U||=1281},Oa:(a,b)=>{if(2>W.version)return U||=1282,0;var c=ub[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Eb().map(Hb),c=ub[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},D:(a,b)=>{b=G(b);if(a=Q[a]){var c=a,d=c.lc,
e=c.Uc,h;if(!d){c.lc=d={};c.Tc={};var g=O.getProgramParameter(c,35718);for(h=0;h<g;++h){var l=O.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Ib(n);q=0<q?n.slice(0,q):n;var u=c.Ac;c.Ac+=l;e[q]=[l,u];for(n=0;n<l;++n)d[u]=n,c.Tc[u++]=q}}c=a.lc;d=0;e=b;h=Ib(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Uc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else U||=1281;return-1},qb:(a,b,c)=>{for(var d=Db[b],e=0;e<b;e++)d[e]=r[c+4*e>>2];O.invalidateFramebuffer(a,
d)},F:a=>{a=Q[a];O.linkProgram(a);a.lc=0;a.Uc={}},La:(a,b)=>{3317==a?vb=b:3314==a&&(wb=b);O.pixelStorei(a,b)},y:(a,b)=>O.polygonOffset(a,b),sb:a=>O.readBuffer(a),va:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),G:(a,b,c)=>{O.samplerParameterf(T[a],b,c)},d:(a,b,c)=>{O.samplerParameteri(T[a],b,c)},A:(a,b,c,d)=>O.scissor(a,b,c,d),hb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h)e+=G(x[c+4*h>>2],d?x[d+4*h>>2]:void 0);O.shaderSource(S[a],e)},pb:(a,b,c)=>O.stencilFunc(a,b,c),qa:(a,b,c,d)=>O.stencilFuncSeparate(a,
b,c,d),m:a=>O.stencilMask(a),ob:(a,b,c)=>O.stencilOp(a,b,c),pa:(a,b,c,d)=>O.stencilOpSeparate(a,b,c,d),Fa:(a,b,c,d,e)=>O.texStorage2D(a,b,c,d,e),Ea:(a,b,c,d,e,h)=>O.texStorage3D(a,b,c,d,e,h),lb:(a,b,c,d,e,h,g,l,n)=>{if(2<=W.version){if(O.kc){O.texSubImage2D(a,b,c,d,e,h,g,l,n);return}if(n){var q=Jb(l);O.texSubImage2D(a,b,c,d,e,h,g,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Jb(l);var u=h*((wb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT+
vb-1&-vb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+u>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;O.texSubImage2D(a,b,c,d,e,h,g,l,n)},jb:(a,b,c,d,e,h,g,l,n,q,u)=>{if(O.kc)O.texSubImage3D(a,b,c,d,e,h,g,l,n,q,u);else if(u){var N=Jb(q);O.texSubImage3D(a,b,c,d,e,h,g,l,n,q,N,u>>>31-Math.clz32(N.BYTES_PER_ELEMENT))}else O.texSubImage3D(a,b,c,d,e,h,g,l,n,q,null)},Fb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1fv(X(a),v,c>>2,b);else{if(288>=b)for(var d=Y[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=
v.subarray(c>>2,c+4*b>>2);O.uniform1fv(X(a),d)}},za:(a,b)=>{O.uniform1i(X(a),b)},Bb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1iv(X(a),r,c>>2,b);else{if(288>=b)for(var d=Kb[b],e=0;e<b;++e)d[e]=r[c+4*e>>2];else d=r.subarray(c>>2,c+4*b>>2);O.uniform1iv(X(a),d)}},Eb:(a,b,c)=>{if(2<=W.version)b&&O.uniform2fv(X(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Y[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);O.uniform2fv(X(a),d)}},Ab:(a,b,c)=>{if(2<=W.version)b&&O.uniform2iv(X(a),
r,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Kb[b],e=0;e<b;e+=2)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2]}else d=r.subarray(c>>2,c+8*b>>2);O.uniform2iv(X(a),d)}},Db:(a,b,c)=>{if(2<=W.version)b&&O.uniform3fv(X(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Y[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);O.uniform3fv(X(a),d)}},zb:(a,b,c)=>{if(2<=W.version)b&&O.uniform3iv(X(a),r,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Kb[b],e=0;e<b;e+=3)d[e]=
r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2]}else d=r.subarray(c>>2,c+12*b>>2);O.uniform3iv(X(a),d)}},Cb:(a,b,c)=>{if(2<=W.version)b&&O.uniform4fv(X(a),v,c>>2,4*b);else{if(72>=b){var d=Y[4*b],e=v;c>>=2;b*=4;for(var h=0;h<b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=v.subarray(c>>2,c+16*b>>2);O.uniform4fv(X(a),d)}},yb:(a,b,c)=>{if(2<=W.version)b&&O.uniform4iv(X(a),r,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Kb[b],e=0;e<b;e+=4)d[e]=r[c+4*e>>2],d[e+1]=r[c+
(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2],d[e+3]=r[c+(4*e+12)>>2]}else d=r.subarray(c>>2,c+16*b>>2);O.uniform4iv(X(a),d)}},xb:(a,b,c,d)=>{if(2<=W.version)b&&O.uniformMatrix4fv(X(a),!!c,v,d>>2,16*b);else{if(18>=b){var e=Y[16*b],h=v;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=
v.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(X(a),!!c,e)}},l:a=>{a=Q[a];O.useProgram(a);O.Wc=a},Hb:(a,b)=>{O.vertexAttribDivisor(a,b)},Ib:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},Jb:(a,b,c,d,e,h)=>{O.vertexAttribPointer(a,b,c,!!d,e,h)},B:(a,b,c,d)=>O.viewport(a,b,c,d),Ba:Ca,bb:function(){f.Nc=a=>{0!=Ub()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Nc)},ab:function(){f.Sc=a=>{const b=a.clipboardData.getData("text");Pb(()=>{const c=Mb(b);Tb(c)})};window.addEventListener("paste",
f.Sc)},$a:function(){f.Ad=[];f.Oc=b=>{b.stopPropagation();b.preventDefault()};f.Pc=b=>{b.stopPropagation();b.preventDefault()};f.Qc=b=>{b.stopPropagation();b.preventDefault()};f.Rc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Bd=c;Vb(c.length);for(let e=0;e<c.length;e++)Pb(()=>{const h=Mb(c[e].name);Wb(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Xb(b.clientX,b.clientY,d)};const a=f.ic;a.addEventListener("dragenter",f.Oc,!1);a.addEventListener("dragleave",
f.Pc,!1);a.addEventListener("dragover",f.Qc,!1);a.addEventListener("drop",f.Rc,!1)},Wa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Xa:function(a){f.qc&&(URL.revokeObjectURL(f.qc[a].cd),f.qc[a]=null)},Lb:function(a,b){0!==b&&(document.title=G(b));a=G(a);void 0!==f.canvas&&("object"===typeof f.canvas?Ya[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.ic=H(a);f.ic||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);f.ic.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Sa:function(){window.removeEventListener("beforeunload",f.Nc)},Ra:function(){window.removeEventListener("paste",f.Sc)},Qa:function(){const a=f.ic;a.removeEventListener("dragenter",f.Oc);a.removeEventListener("dragleave",f.Pc);a.removeEventListener("dragover",f.Qc);a.removeEventListener("drop",f.Rc)},t:function(){f.ic&&f.ic.requestPointerLock&&f.ic.requestPointerLock()},Ya:function(a,b,c){if(f.ic){if(0===
b)a="none";else if(0!=c)a=f.qc[a].ed;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.ic.style.cursor=a}},Va:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,
b);h.data.set(y.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},da:function(a,b){b=G(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function ac(a=[]){var b=Sb;a.unshift(ea);var c=a.length,d=Lb(4*(c+1)),e=d,h;for(h of a)x[e>>2]=Mb(h),e+=4;x[e>>2]=0;try{var g=b(c,d);ma=g;Ca(g)}catch(l){Ba(l)}}
function bc(a=da){function b(){f.calledRun=!0;if(!p){cc.Nb();f.onRuntimeInitialized?.();f.noInitialRun||ac(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();wa.push(c)}va(wa)}}if(0<z)A=bc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();va(xa);0<z?A=bc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}var cc;
(async function(){function a(c){c=cc=c.exports;Sb=f._main=c.Ob;Tb=f.__sapp_emsc_onpaste=c.Pb;Ub=f.__sapp_html5_get_ask_leave_site=c.Qb;Vb=f.__sapp_emsc_begin_drop=c.Rb;Wb=f.__sapp_emsc_drop=c.Sb;Xb=f.__sapp_emsc_end_drop=c.Tb;f.__sapp_emsc_invoke_fetch_cb=c.Ub;f.__sapp_emsc_set_fullscreen_flag=c.Vb;Yb=c.Wb;L=c.Xb;Ob=c.Yb;Lb=c.Zb;Nb=c._b;Zb=c.Mb;M=c.$b;c=Zb.buffer;t=new Int8Array(c);ta=new Int16Array(c);y=new Uint8Array(c);ua=new Uint16Array(c);r=new Int32Array(c);x=new Uint32Array(c);v=new Float32Array(c);
w=new Float64Array(c);new BigInt64Array(c);new BigUint64Array(c);z--;f.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return cc}z++;f.monitorRunDependencies?.(z);var b={a:$b};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});oa??=f.locateFile?f.locateFile("sulkyos.wasm",ia):ia+"sulkyos.wasm";return a((await ra(b)).instance)})();bc();
