var f;f||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m,p=!1,na,la=a=>a.startsWith("file://");
function oa(a){f.onAbort?.(a);a=`Aborted(${a})`;k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var pa;async function qa(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==pa&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function ra(a,b){try{var c=await qa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),oa(d)}}
async function sa(a){var b=pa;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ra(b,a)}class ta{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ua,r,u,v,w,va,x,y,wa=a=>{for(;0<a.length;)a.shift()(f)},xa=[],ya=[],za=()=>{var a=f.preRun.shift();ya.push(a)},z=0,A=null,Aa=!0,Ba=0,C={},Ca=a=>{a instanceof ta||"unwind"==a||fa(1,a)},Da=a=>{na=a;Aa||0<Ba||(f.onExit?.(a),p=!0);fa(a,new ta(a))},Ea=()=>{if(!(Aa||0<Ba))try{var a=na;na=a;Da(a)}catch(b){Ca(b)}},Fa=a=>{if(!p)try{a()}catch(b){Ca(b)}finally{Ea()}},Ma=(a,b)=>{Ga=a;Ha=b;if(E)if(Ia||=!0,0==a)F=function(){setTimeout(G,Math.max(0,Ja+b-performance.now())|0)};else if(1==a)F=function(){Ka(G)};
else{if(!La)if(globalThis.setImmediate)La=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);La=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}F=function(){La(G)}}},Va=(a,b,c,d,e)=>{function h(){return g<Na?(Ea(),!1):!0}E=a;Oa=d;var g=Na;Ia=!1;G=function(){if(!p)if(0<Pa.length){var l=
Pa.shift();l.pd(l.bd);if(Qa){var n=Qa,q=0==n%1?n-1:Math.floor(n);Qa=l.ed?q:(8*n+(q+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",n=Qa??0,q=Ra.md??0,n?n<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(G,0)}else if(h())if(Sa=Sa+1|0,1==Ga&&1<Ha&&0!=Sa%Ha)F();else{0==Ga&&(Ja=performance.now());a:if(!p){for(l of Ta)if(!1===l())break a;Fa(a);for(n of Ua)n()}h()&&F()}};e||(0<b?Ma(0,1E3/b):Ma(1,1),F());if(c)throw"unwind";},Ia=!1,F=
null,Na=0,E=null,Oa=0,Ga=0,Ha=0,Sa=0,Pa=[],Ta=[],Ua=[];function Wa(){F=null;Na++}var Xa=0;function Ka(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Xa)Xa=b+1E3/60;else for(;b+2>=Xa;)Xa+=1E3/60;setTimeout(a,Math.max(Xa-b,0))}}
var Ra={},Ja,G,La,Qa,Ya=new TextDecoder,Za=(a,b,c)=>{for(c=b+c;a[b]&&!(b>=c);)++b;return b},H=(a,b)=>a?Ya.decode(y.subarray(a,Za(y,a,b))):"",$a=[0,globalThis.document??0,globalThis.window??0],I=a=>{a=2<a?H(a):a;return $a[a]||globalThis.document?.querySelector(a)},ab=a=>0>$a.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};function bb(a){var b=J.cc[a];b.target.removeEventListener(b.bc,b.Jc,b.fc);J.cc.splice(a,1)}
function cb(){if(navigator.userActivation?navigator.userActivation.isActive:J.vc&&J.Wc.sc){var a=J.kc;J.kc=[];for(var b of a)b.yc(...b.Ec)}}function K(a){if(!a.target)return-4;if(a.dc)a.Jc=function(c){++J.vc;J.Wc=a;cb();a.ic(c);cb();--J.vc},a.target.addEventListener(a.bc,a.Jc,a.fc),J.cc.push(a);else for(var b=0;b<J.cc.length;++b)J.cc[b].target==a.target&&J.cc[b].bc==a.bc&&bb(b--);return 0}function db(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var J={cd:0,qd:0,wc:0,qc:0,Cc:0,Ac:0,tc:0,kd:0,ud:0,jd:0,uc:0,xc:0,Ed:0,zc:0,wd(){for(;J.cc.length;)bb(J.cc.length-1);J.kc=[]},vc:0,kc:[],hd(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var e of J.kc)if(e.yc==a&&d(e.Ec,c))return;J.kc.push({yc:a,Nc:b,Ec:c});J.kc.sort((h,g)=>h.Nc-g.Nc)},yd(a){J.kc=J.kc.filter(b=>b.yc!=a)},cc:[],xd:(a,b)=>{for(var c=0;c<J.cc.length;++c)J.cc[c].target!=a||b&&b!=J.cc[c].bc||bb(c--)},zd(a){let b=!1;for(let c=0;c<
J.cc.length;++c){const d=J.cc[c];d.target===a.target&&d.ec===a.ec&&d.dc===a.dc&&d.hc===a.hc&&(bb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},L=(a,b,c)=>{var d=y;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&
63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;h++}}d[b]=0;return b-e},eb=(a,b,c,d,e,h)=>{J.tc||(J.tc=M(256));a={target:I(a),bc:h,ec:e,hc:b,dc:d,ic:g=>{var l=g.target.id?g.target.id:"",n=J.tc;L(db(g.target),n+0,128);L(l,n+128,128);N.get(d)(e,n,b)&&g.preventDefault()},fc:c};return K(a)},fb=(a,b,c,d,e)=>{J.uc||(J.uc=M(276));return K({target:a,bc:e,ec:19,hc:b,dc:d,ic:h=>{var g=J.uc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;u[g]=n;u[g+1]=J.fullscreenEnabled();var q=n?l:J.$c,t=q?.id||"";L(db(q),g+2,128);L(t,g+130,128);r[g+260>>2]=q?q.clientWidth:0;r[g+264>>2]=q?q.clientHeight:0;r[g+268>>2]=screen.width;r[g+272>>2]=screen.height;n&&(J.$c=l);N.get(d)(19,g,b)&&h.preventDefault()},fc:c})},gb=(a,b,c,d,e,h)=>{J.wc||(J.wc=M(160));a={target:I(a),bc:h,ec:e,hc:b,dc:d,ic:g=>{var l=J.wc;w[l>>3]=g.timeStamp;var n=l>>2;r[n+2]=g.location;u[l+12]=g.ctrlKey;u[l+
13]=g.shiftKey;u[l+14]=g.altKey;u[l+15]=g.metaKey;u[l+16]=g.repeat;r[n+5]=g.charCode;r[n+6]=g.keyCode;r[n+7]=g.which;L(g.key||"",l+32,32);L(g.code||"",l+64,32);L(g.char||"",l+96,32);L(g.locale||"",l+128,32);N.get(d)(e,l,b)&&g.preventDefault()},fc:c};return K(a)},hb=(a,b,c)=>{w[a>>3]=b.timeStamp;var d=a>>2;r[d+2]=b.screenX;r[d+3]=b.screenY;r[d+4]=b.clientX;r[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;ua[2*d+14]=b.button;ua[2*d+15]=b.buttons;r[d+8]=b.movementX;
r[d+9]=b.movementY;a=ab(c);r[d+10]=b.clientX-(a.left|0);r[d+11]=b.clientY-(a.top|0)},ib=(a,b,c,d,e,h)=>{J.qc||(J.qc=M(64));a=I(a);return K({target:a,sc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,bc:h,ec:e,hc:b,dc:d,ic:g=>{hb(J.qc,g,a);N.get(d)(e,J.qc,b)&&g.preventDefault()},fc:c})},jb=(a,b,c,d)=>{J.xc||(J.xc=M(257));return K({target:a,bc:"pointerlockchange",ec:20,hc:b,dc:d,ic:e=>{var h=J.xc,g=document.pointerLockElement;u[h]=!!g;var l=g?.id||"";L(db(g),h+1,128);L(l,h+129,128);N.get(d)(20,h,
b)&&e.preventDefault()},fc:c})},kb=(a,b,c,d)=>K({target:a,bc:"pointerlockerror",ec:38,hc:b,dc:d,ic:e=>{N.get(d)(38,0,b)&&e.preventDefault()},fc:c}),lb=(a,b,c,d)=>{J.Ac||(J.Ac=M(36));a=I(a);return K({target:a,bc:"resize",ec:10,hc:b,dc:d,ic:e=>{if(e.target==a){var h=document.body;if(h){var g=J.Ac;r[g>>2]=0;r[g+4>>2]=h.clientWidth;r[g+8>>2]=h.clientHeight;r[g+12>>2]=innerWidth;r[g+16>>2]=innerHeight;r[g+20>>2]=outerWidth;r[g+24>>2]=outerHeight;r[g+28>>2]=pageXOffset|0;r[g+32>>2]=pageYOffset|0;N.get(d)(10,
g,b)&&e.preventDefault()}}},fc:c})},mb=(a,b,c,d,e,h)=>{J.zc||(J.zc=M(1552));a=I(a);return K({target:a,sc:"touchstart"==h||"touchend"==h,bc:h,ec:e,hc:b,dc:d,ic:g=>{var l={},n=g.touches;for(var q of n)q.Kc=q.Mc=0,l[q.identifier]=q;for(var t of g.changedTouches)t.Kc=1,l[t.identifier]=t;for(var B of g.targetTouches)l[B.identifier].Mc=1;n=J.zc;w[n>>3]=g.timeStamp;u[n+12]=g.ctrlKey;u[n+13]=g.shiftKey;u[n+14]=g.altKey;u[n+15]=g.metaKey;q=n+16;t=ab(a);B=0;for(let D of Object.values(l))if(l=q>>2,r[l]=D.identifier,
r[l+1]=D.screenX,r[l+2]=D.screenY,r[l+3]=D.clientX,r[l+4]=D.clientY,r[l+5]=D.pageX,r[l+6]=D.pageY,u[q+28]=D.Kc,u[q+29]=D.Mc,r[l+8]=D.clientX-(t.left|0),r[l+9]=D.clientY-(t.top|0),q+=48,31<++B)break;r[n+8>>2]=B;N.get(d)(e,n,b)&&g.preventDefault()},fc:c})},O,nb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,
d,e,h,g))},ob=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},pb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},qb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},rb=1,P=[],Q=[],sb=[],tb=[],R=[],S=[],ub=[],vb=[],T=[],wb={},xb=4,yb=0,zb=a=>{for(var b=rb++,c=a.length;c<b;c++)a[c]=null;return b},V=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=O[c](),g=h&&zb(d);h?(h.name=g,d[g]=h):U||=1282;r[b+4*e>>2]=g}},Bb=(a,b)=>{a.Fc||(a.Fc=a.getContext,a.getContext=function(d,e){e=a.Fc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Lc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Ab(c,b):0},Ab=(a,b)=>{var c=zb(vb),d={handle:c,attributes:b,version:b.Lc,Dc:a};a.canvas&&(a.canvas.ad=d);vb[c]=d;if("undefined"==typeof b.Ic||b.Ic)if((a=d)||(a=W),!a.Zc){a.Zc=!0;b=a.Dc;b.td=b.getExtension("WEBGL_multi_draw");b.od=b.getExtension("EXT_polygon_offset_clamp");b.nd=b.getExtension("EXT_clip_control");b.Fd=b.getExtension("WEBGL_polygon_mode");nb(b);ob(b);pb(b);b.ld=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.rd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Hc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Hc)b.Hc=b.getExtension("EXT_disjoint_timer_query");for(var e of qb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},U,W,Cb=(a,b,c,d,e,h)=>{a={target:I(a),bc:h,ec:e,hc:b,dc:d,ic:g=>{N.get(d)(e,0,b)&&g.preventDefault()},fc:c};K(a)},Db=(a,b,c,d)=>{J.Cc||(J.Cc=M(96));return K({target:a,sc:!0,bc:"wheel",ec:9,hc:b,dc:d,ic:e=>{var h=J.Cc;hb(h,e,a);w[h+64>>3]=e.deltaX;w[h+72>>3]=e.deltaY;
w[h+80>>3]=e.deltaZ;r[h+88>>2]=e.deltaMode;N.get(d)(9,h,b)&&e.preventDefault()},fc:c})},Eb=["default","low-power","high-performance"],Fb=[null,[],[]],Gb=[],Hb=()=>{var a=qb(O);return a=a.concat(a.map(b=>"GL_"+b))},Ib=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>W.version){U||=1282;return}c=Hb().length;break;case 33307:case 33308:if(2>W.version){U||=1280;return}c=
33307==a?3:0}if(void 0===c)switch(d=O.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||
d instanceof Array){for(a=0;a<d.length;++a)r[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}r[b>>2]=c}else U||=1281},Jb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},
Kb=a=>{var b=Jb(a)+1,c=M(b);c&&L(a,c,b);return c},Lb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Mb=a=>{a-=5120;return 0==a?u:1==a?y:2==a?ua:4==a?r:6==a?v:5==a||28922==a||28520==a||30779==a||30782==a?x:va},X=a=>{var b=O.Xc;if(b){var c=b.mc[a];"number"==typeof c&&(b.mc[a]=c=O.getUniformLocation(b,b.Uc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},Y=[],Nb=[],Pb=a=>{var b=Jb(a)+1,c=Ob(b);L(a,c,b);return c},Sb=a=>{var b=Qb();a();Rb(b)};f.requestAnimationFrame=Ka;f.pauseMainLoop=Wa;
f.resumeMainLoop=function(){Na++;var a=Ga,b=Ha,c=E;E=null;Va(c,0,!1,Oa,!0);Ma(a,b);F()};f.preMainLoop&&Ta.push(f.preMainLoop);f.postMainLoop&&Ua.push(f.postMainLoop);for(let a=0;32>a;++a)Gb.push(Array(a));for(var Tb=new Float32Array(288),Z=0;288>=Z;++Z)Y[Z]=Tb.subarray(0,Z);var Ub=new Int32Array(288);for(Z=0;288>=Z;++Z)Nb[Z]=Ub.subarray(0,Z);f.noExitRuntime&&(Aa=f.noExitRuntime);f.print&&(ma=f.print);f.printErr&&(k=f.printErr);f.wasmBinary&&(m=f.wasmBinary);f.arguments&&(da=f.arguments);
f.thisProgram&&(ea=f.thisProgram);if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();
var Vb,Wb,Xb,Yb,Zb,$b,ac,M,Rb,Ob,Qb,bc,N,cc={Ma:()=>oa(""),Ia:()=>{Aa=!1;Ba=0},cb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Fa(()=>ac(a,performance.now()))},b);C[a]={id:c,Dd:b};return 0},Ta:()=>{Wa();E=null},P:()=>globalThis.devicePixelRatio??1,oa:(a,b,c)=>{a=I(a);if(!a)return-4;a=ab(a);w[b>>3]=a.width;w[c>>3]=a.height;return 0},Ua:()=>performance.now(),Za:(a,b)=>{function c(d){N.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
Pa:()=>{oa("OOM")},R:(a,b,c,d)=>eb(a,b,c,d,12,"blur"),M:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},S:(a,b,c,d)=>eb(a,b,c,d,13,"focus"),Q:(a,b,c,d)=>{if(!J.fullscreenEnabled())return-1;a=I(a);if(!a)return-4;fb(a,b,c,d,"webkitfullscreenchange");return fb(a,b,c,d,"fullscreenchange")},aa:(a,b,c,d)=>gb(a,b,c,d,2,"keydown"),_:(a,b,c,d)=>gb(a,b,c,d,1,"keypress"),$:(a,b,c,d)=>gb(a,b,c,d,3,"keyup"),_a:(a,b,c)=>{a=N.get(a);Va(a,b,c)},ja:(a,b,c,d)=>ib(a,b,c,d,5,"mousedown"),fa:(a,b,c,d)=>
ib(a,b,c,d,33,"mouseenter"),ca:(a,b,c,d)=>ib(a,b,c,d,34,"mouseleave"),ga:(a,b,c,d)=>ib(a,b,c,d,8,"mousemove"),ia:(a,b,c,d)=>ib(a,b,c,d,6,"mouseup"),U:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?jb(a,b,c,d):-4:-1,T:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?kb(a,b,c,d):-4:-1,Z:(a,b,c,d)=>lb(a,b,c,d),V:(a,b,c,d)=>mb(a,b,c,d,25,"touchcancel"),W:(a,b,c,d)=>mb(a,b,c,d,23,"touchend"),X:(a,b,c,d)=>mb(a,b,c,d,24,"touchmove"),Y:(a,b,c,d)=>mb(a,b,c,d,22,"touchstart"),O:(a,b,c,d)=>{Cb(a,
b,c,d,31,"webglcontextlost");return 0},N:(a,b,c,d)=>{Cb(a,b,c,d,32,"webglcontextrestored");return 0},ba:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?Db(a,b,c,d):-1:-4,ua:(a,b)=>{var c=b>>2;b={alpha:!!u[b+0],depth:!!u[b+1],stencil:!!u[b+2],antialias:!!u[b+3],premultipliedAlpha:!!u[b+4],preserveDrawingBuffer:!!u[b+5],powerPreference:Eb[r[c+2]],failIfMajorPerformanceCaveat:!!u[b+12],Lc:r[c+4],sd:r[c+5],Ic:u[b+24],Yc:u[b+25],vd:r[c+7],Ad:u[b+32]};a=I(a);return!a||b.Yc?0:Bb(a,b)},ta:a=>{W=vb[a];f.ctx=
O=W?.Dc;return!a||O?0:-5},db:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var g=x[b>>2],l=x[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=a,t=y[g+n],B=Fb[q];0===t||10===t?(q=1===q?ma:k,t=Za(B,0),t=Ya.decode(B.buffer?B.subarray(0,t):new Uint8Array(B.slice(0,t))),q(t),B.length=0):B.push(t)}e+=l}x[d>>2]=e;return 0},v:a=>O.activeTexture(a),r:(a,b)=>{O.attachShader(Q[a],S[b])},b:(a,b)=>{35051==a?O.Gc=b:35052==a&&(O.lc=b);O.bindBuffer(a,P[b])},ha:(a,b,c)=>{O.bindBufferBase(a,b,P[c])},Lb:(a,b,c,d,e)=>{O.bindBufferRange(a,
b,P[c],d,e)},f:(a,b)=>{O.bindFramebuffer(a,sb[b])},wa:(a,b)=>{O.bindRenderbuffer(a,tb[b])},u:(a,b)=>{O.bindSampler(a,T[b])},g:(a,b)=>{O.bindTexture(a,R[b])},L:a=>{O.bindVertexArray(ub[a])},na:(a,b,c,d)=>O.blendColor(a,b,c,d),w:(a,b)=>O.blendEquationSeparate(a,b),x:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),sb:(a,b,c,d,e,h,g,l,n,q)=>O.blitFramebuffer(a,b,c,d,e,h,g,l,n,q),Ha:(a,b,c,d)=>{2<=W.version?c&&b?O.bufferData(a,y,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?y.subarray(c,c+b):b,d)},H:(a,b,c,d)=>
{2<=W.version?c&&O.bufferSubData(a,b,y,d,c):O.bufferSubData(a,b,y.subarray(d,d+c))},eb:a=>O.checkFramebufferStatus(a),sa:(a,b,c,d)=>O.clearBufferfi(a,b,c,d),z:(a,b,c)=>{O.clearBufferfv(a,b,v,c>>2)},ra:(a,b,c)=>{O.clearBufferiv(a,b,r,c>>2)},n:(a,b,c,d)=>{O.colorMask(!!a,!!b,!!c,!!d)},hb:a=>{O.compileShader(S[a])},nb:(a,b,c,d,e,h,g,l,n)=>{2<=W.version?O.lc||!l?O.compressedTexSubImage2D(a,b,c,d,e,h,g,l,n):O.compressedTexSubImage2D(a,b,c,d,e,h,g,y,n,l):O.compressedTexSubImage2D(a,b,c,d,e,h,g,y.subarray(n,
n+l))},lb:(a,b,c,d,e,h,g,l,n,q,t)=>{O.lc?O.compressedTexSubImage3D(a,b,c,d,e,h,g,l,n,q,t):O.compressedTexSubImage3D(a,b,c,d,e,h,g,l,n,y,t,q)},Ca:()=>{var a=zb(Q),b=O.createProgram();b.name=a;b.pc=b.nc=b.oc=0;b.Bc=1;Q[a]=b;return a},jb:a=>{var b=zb(S);S[b]=O.createShader(a);return b},ma:a=>O.cullFace(a),ob:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=P[d];e&&(O.deleteBuffer(e),e.name=0,P[d]=null,d==O.Gc&&(O.Gc=0),d==O.lc&&(O.lc=0))}},s:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+4*c>>2],e=sb[d];e&&
(O.deleteFramebuffer(e),e.name=0,sb[d]=null)}},k:a=>{if(a){var b=Q[a];b?(O.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},I:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=tb[d];e&&(O.deleteRenderbuffer(e),e.name=0,tb[d]=null)}},J:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=T[d];e&&(O.deleteSampler(e),e.name=0,T[d]=null)}},j:a=>{if(a){var b=S[a];b?(O.deleteShader(b),S[a]=null):U||=1281}},o:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=R[d];e&&(O.deleteTexture(e),e.name=0,R[d]=null)}},Ka:(a,
b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2];O.deleteVertexArray(ub[d]);ub[d]=null}},p:a=>O.depthFunc(a),q:a=>{O.depthMask(!!a)},c:a=>O.disable(a),ka:a=>{O.disableVertexAttribArray(a)},ub:(a,b,c)=>{O.drawArrays(a,b,c)},vb:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},C:(a,b)=>{for(var c=Gb[a],d=0;d<a;d++)c[d]=r[b+4*d>>2];O.drawBuffers(c)},wb:(a,b,c,d)=>{O.drawElements(a,b,c,d)},xb:(a,b,c,d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},e:a=>O.enable(a),Hb:a=>{O.enableVertexAttribArray(a)},i:(a,b,c,d)=>{O.framebufferRenderbuffer(a,
b,c,tb[d])},h:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,R[d],e)},fb:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,b,R[c],d,e)},la:a=>O.frontFace(a),Ja:(a,b)=>{V(a,b,"createBuffer",P)},K:(a,b)=>{V(a,b,"createFramebuffer",sb)},xa:(a,b)=>{V(a,b,"createRenderbuffer",tb)},Da:(a,b)=>{V(a,b,"createSampler",T)},Ga:(a,b)=>{V(a,b,"createTexture",R)},Na:(a,b)=>{V(a,b,"createVertexArray",ub)},ya:(a,b)=>O.getAttribLocation(Q[a],H(b)),a:(a,b)=>Ib(a,b),Aa:(a,b,c,d)=>{a=O.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");
b=0<b&&d?L(a,d,b):0;c&&(r[c>>2]=b)},E:(a,b,c)=>{if(c)if(a>=rb)U||=1281;else if(a=Q[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(35719==b){if(!a.pc){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.pc=Math.max(a.pc,O.getActiveUniform(a,b).name.length+1)}r[c>>2]=a.pc}else if(35722==b){if(!a.nc)for(d=O.getProgramParameter(a,35721),b=0;b<d;++b)a.nc=Math.max(a.nc,O.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.nc}else if(35381==b){if(!a.oc)for(d=
O.getProgramParameter(a,35382),b=0;b<d;++b)a.oc=Math.max(a.oc,O.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.oc}else r[c>>2]=O.getProgramParameter(a,b);else U||=1281},gb:(a,b,c,d)=>{a=O.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(r[c>>2]=b)},ea:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(S[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=O.getShaderParameter(S[a],b):U||=1281},Oa:(a,
b)=>{if(2>W.version)return U||=1282,0;var c=wb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Hb().map(Kb),c=wb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},D:(a,b)=>{b=H(b);if(a=Q[a]){var c=a,d=c.mc,e=c.Vc,h;if(!d){c.mc=d={};c.Uc={};var g=O.getProgramParameter(c,35718);for(h=0;h<g;++h){var l=O.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Lb(n);q=0<q?n.slice(0,q):n;var t=c.Bc;c.Bc+=l;e[q]=[l,t];for(n=0;n<l;++n)d[t]=n,c.Uc[t++]=q}}c=a.mc;
d=0;e=b;h=Lb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Vc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else U||=1281;return-1},rb:(a,b,c)=>{for(var d=Gb[b],e=0;e<b;e++)d[e]=r[c+4*e>>2];O.invalidateFramebuffer(a,d)},F:a=>{a=Q[a];O.linkProgram(a);a.mc=0;a.Vc={}},La:(a,b)=>{3317==a?xb=b:3314==a&&(yb=b);O.pixelStorei(a,b)},y:(a,b)=>O.polygonOffset(a,b),tb:a=>O.readBuffer(a),va:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),G:(a,b,c)=>{O.samplerParameterf(T[a],
b,c)},d:(a,b,c)=>{O.samplerParameteri(T[a],b,c)},A:(a,b,c,d)=>O.scissor(a,b,c,d),ib:(a,b,c,d)=>{for(var e="",h=0;h<b;++h)e+=H(x[c+4*h>>2],d?x[d+4*h>>2]:void 0);O.shaderSource(S[a],e)},qb:(a,b,c)=>O.stencilFunc(a,b,c),qa:(a,b,c,d)=>O.stencilFuncSeparate(a,b,c,d),m:a=>O.stencilMask(a),pb:(a,b,c)=>O.stencilOp(a,b,c),pa:(a,b,c,d)=>O.stencilOpSeparate(a,b,c,d),Fa:(a,b,c,d,e)=>O.texStorage2D(a,b,c,d,e),Ea:(a,b,c,d,e,h)=>O.texStorage3D(a,b,c,d,e,h),mb:(a,b,c,d,e,h,g,l,n)=>{if(2<=W.version){if(O.lc){O.texSubImage2D(a,
b,c,d,e,h,g,l,n);return}if(n){var q=Mb(l);O.texSubImage2D(a,b,c,d,e,h,g,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Mb(l);var t=h*((yb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT+xb-1&-xb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+t>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;O.texSubImage2D(a,b,c,d,e,h,g,l,n)},kb:(a,b,c,d,e,h,g,l,n,q,t)=>{if(O.lc)O.texSubImage3D(a,b,c,d,e,h,g,l,n,q,t);else if(t){var B=Mb(q);
O.texSubImage3D(a,b,c,d,e,h,g,l,n,q,B,t>>>31-Math.clz32(B.BYTES_PER_ELEMENT))}else O.texSubImage3D(a,b,c,d,e,h,g,l,n,q,null)},Gb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1fv(X(a),v,c>>2,b);else{if(288>=b)for(var d=Y[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);O.uniform1fv(X(a),d)}},za:(a,b)=>{O.uniform1i(X(a),b)},Cb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1iv(X(a),r,c>>2,b);else{if(288>=b)for(var d=Nb[b],e=0;e<b;++e)d[e]=r[c+4*e>>2];else d=r.subarray(c>>2,c+4*b>>2);O.uniform1iv(X(a),
d)}},Fb:(a,b,c)=>{if(2<=W.version)b&&O.uniform2fv(X(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Y[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);O.uniform2fv(X(a),d)}},Bb:(a,b,c)=>{if(2<=W.version)b&&O.uniform2iv(X(a),r,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Nb[b],e=0;e<b;e+=2)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2]}else d=r.subarray(c>>2,c+8*b>>2);O.uniform2iv(X(a),d)}},Eb:(a,b,c)=>{if(2<=W.version)b&&O.uniform3fv(X(a),v,c>>2,3*b);else{if(96>=b){b*=3;
for(var d=Y[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);O.uniform3fv(X(a),d)}},Ab:(a,b,c)=>{if(2<=W.version)b&&O.uniform3iv(X(a),r,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Nb[b],e=0;e<b;e+=3)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2]}else d=r.subarray(c>>2,c+12*b>>2);O.uniform3iv(X(a),d)}},Db:(a,b,c)=>{if(2<=W.version)b&&O.uniform4fv(X(a),v,c>>2,4*b);else{if(72>=b){var d=Y[4*b],e=v;c>>=2;b*=4;for(var h=0;h<b;h+=
4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=v.subarray(c>>2,c+16*b>>2);O.uniform4fv(X(a),d)}},zb:(a,b,c)=>{if(2<=W.version)b&&O.uniform4iv(X(a),r,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Nb[b],e=0;e<b;e+=4)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2],d[e+3]=r[c+(4*e+12)>>2]}else d=r.subarray(c>>2,c+16*b>>2);O.uniform4iv(X(a),d)}},yb:(a,b,c,d)=>{if(2<=W.version)b&&O.uniformMatrix4fv(X(a),!!c,v,d>>2,16*b);else{if(18>=b){var e=Y[16*b],h=v;d>>=2;b*=16;for(var g=
0;g<b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=v.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(X(a),!!c,e)}},l:a=>{a=Q[a];O.useProgram(a);O.Xc=a},Ib:(a,b)=>{O.vertexAttribDivisor(a,b)},Jb:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},Kb:(a,b,c,d,e,h)=>{O.vertexAttribPointer(a,b,c,!!d,
e,h)},B:(a,b,c,d)=>O.viewport(a,b,c,d),Ba:Da,bb:function(){f.Oc=a=>{0!=Xb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Oc)},ab:function(){f.Tc=a=>{const b=a.clipboardData.getData("text");Sb(()=>{const c=Pb(b);Wb(c)})};window.addEventListener("paste",f.Tc)},$a:function(){f.Bd=[];f.Pc=b=>{b.stopPropagation();b.preventDefault()};f.Qc=b=>{b.stopPropagation();b.preventDefault()};f.Rc=b=>{b.stopPropagation();b.preventDefault()};f.Sc=b=>{b.stopPropagation();b.preventDefault();
const c=b.dataTransfer.files;f.Cd=c;Yb(c.length);for(let e=0;e<c.length;e++)Sb(()=>{const h=Pb(c[e].name);Zb(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);$b(b.clientX,b.clientY,d)};const a=f.jc;a.addEventListener("dragenter",f.Pc,!1);a.addEventListener("dragleave",f.Qc,!1);a.addEventListener("dragover",f.Rc,!1);a.addEventListener("drop",f.Sc,!1)},Wa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Xa:function(a){f.rc&&
(URL.revokeObjectURL(f.rc[a].dd),f.rc[a]=null)},Mb:function(a,b){0!==b&&(document.title=H(b));a=H(a);void 0!==f.canvas&&("object"===typeof f.canvas?$a[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.jc=I(a);f.jc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.jc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Sa:function(){window.removeEventListener("beforeunload",f.Oc)},Ra:function(){window.removeEventListener("paste",
f.Tc)},Qa:function(){const a=f.jc;a.removeEventListener("dragenter",f.Pc);a.removeEventListener("dragleave",f.Qc);a.removeEventListener("dragover",f.Rc);a.removeEventListener("drop",f.Sc)},t:function(){f.jc&&f.jc.requestPointerLock&&f.jc.requestPointerLock()},Ya:function(a,b,c){if(f.jc){if(0===b)a="none";else if(0!=c)a=f.rc[a].gd;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a=
"ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.jc.style.cursor=a}},Va:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(y.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},da:function(a,
b){b=H(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function dc(a=[]){var b=Vb;a.unshift(ea);var c=a.length,d=Ob(4*(c+1)),e=d,h;for(h of a)x[e>>2]=Pb(h),e+=4;x[e>>2]=0;try{var g=b(c,d);na=g;Da(g)}catch(l){Ca(l)}}
function ec(a=da){function b(){f.calledRun=!0;if(!p){fc.Ob();f.onRuntimeInitialized?.();f.noInitialRun||dc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();xa.push(c)}wa(xa)}}if(0<z)A=ec;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)za();wa(ya);0<z?A=ec:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}var fc;
(async function(){function a(c){c=fc=c.exports;Vb=f._main=c.Pb;Wb=f.__sapp_emsc_onpaste=c.Qb;Xb=f.__sapp_html5_get_ask_leave_site=c.Rb;Yb=f.__sapp_emsc_begin_drop=c.Sb;Zb=f.__sapp_emsc_drop=c.Tb;$b=f.__sapp_emsc_end_drop=c.Ub;f.__sapp_emsc_invoke_fetch_cb=c.Vb;f.__sapp_emsc_set_fullscreen_flag=c.Wb;ac=c.Xb;M=c.Yb;Rb=c.Zb;Ob=c._b;Qb=c.$b;bc=c.Nb;N=c.ac;c=bc.buffer;u=new Int8Array(c);ua=new Int16Array(c);y=new Uint8Array(c);va=new Uint16Array(c);r=new Int32Array(c);x=new Uint32Array(c);v=new Float32Array(c);
w=new Float64Array(c);new BigInt64Array(c);new BigUint64Array(c);z--;f.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return fc}z++;f.monitorRunDependencies?.(z);var b={a:cc};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});pa??=f.locateFile?f.locateFile("sulkyos.wasm",ia):ia+"sulkyos.wasm";return a((await sa(b)).instance)})();ec();
